import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { existsSync, readFileSync } from "fs";
import { execSync } from "node:child_process";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Detect entry point: prefer src/main.ts, fallback to main.ts
const hasSrcMain = existsSync("src/main.ts");
const hasRootMain = existsSync("main.ts");

if (hasSrcMain && hasRootMain) {
	console.warn("WARNING: Both src/main.ts and main.ts exist. Using src/main.ts as entry point.");
	console.warn("Consider removing one to avoid confusion.");
}
if (!hasSrcMain && !hasRootMain) {
	console.error("ERROR: Neither src/main.ts nor main.ts found!");
	process.exit(1);
}

// Set entry point based on what exists
const entryPoint = hasSrcMain ? "src/main.ts" : "main.ts";

// Always build to root for simplicity
const outfile = "main.js";

const resolveGitHash = () => {
	if (process.env.GIT_HASH) {
		return process.env.GIT_HASH;
	}
	try {
		return execSync("git rev-parse --short HEAD").toString().trim();
	} catch (error) {
		return "unknown";
	}
};

const resolvePluginVersion = () => {
	if (process.env.PLUGIN_VERSION) {
		return process.env.PLUGIN_VERSION;
	}
	try {
		const manifest = JSON.parse(readFileSync("manifest.json", "utf-8"));
		if (manifest?.version) {
			return manifest.version;
		}
	} catch (error) {
		// ignore
	}
	return process.env.npm_package_version || "unknown";
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [entryPoint],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: "inline",
	treeShaking: true,
	outfile: outfile,
	minify: false,
	define: {
		__PLUGIN_VERSION__: JSON.stringify(resolvePluginVersion()),
		__GIT_HASH__: JSON.stringify(resolveGitHash()),
	},
});

// Check if this is a one-time build or watch mode
// Check for "build" or "production" argument - supports both patterns
const args = process.argv.slice(2);
const isOneTimeBuild = args.includes("build") || args.includes("production");

if (isOneTimeBuild) {
	// Production build: build once and exit
	await context.rebuild();
	console.log("\n✓ Build complete!");
	console.log("📦 Release files:");
	console.log("   - main.js");
	if (existsSync("manifest.json")) {
		console.log("   - manifest.json");
	}
	if (existsSync("styles.css")) {
		console.log("   - styles.css");
	}
	console.log("\n💡 Upload these files to GitHub releases\n");
	await context.dispose();
	process.exit(0);
} else {
	// Development mode: watch for changes
	console.log("\n✓ Development build running in watch mode");
	console.log("📝 Building to main.js in root");
	console.log("💡 For production builds, run: pnpm build\n");
	await context.watch();
}
